feat : axios instance 등 기본 구성
Odagada/Trimo-FE pull request #15
Opened 2024-01-24 17:44 UTC by ayden94

## 🛠️ 주요 변경 사항

- [x] instance 생성
- [x] interceptors를 활용하여 로직 추가
- [x] react query를 위한 공용 fetcher 구성
- [x] 일반적으로 사용하기 위한 request 함수 구성 

## 📣 리뷰어에게 하고싶은 말

- 로직 부분 좀 자세히 확인해주시면 감사하겠습니다.

## 🖼️ 스크린샷(선택)

2024-01-25 07:52 UTC, arky02 requested changes
수고하셨습니다 LGTM! 그리고 지금 빌드 에러 나는 부분에서 이거 안고치고 머지되면 그 이후로 계속 빌드 에러나서 새로 올린 코드에서 빌드 에러를 체크할 수가 없어서 일단 any타입으로라도 빌드 에러 없애든 타입 대충이라도 만들어서 임시로 넣든 해야할 것 같아요!!!!! 일단 리퀘체인지 하겠습니다!

2024-01-25 07:52 UTC, arky02 commented on apis/axios.ts
> +});
timeout을 5초로 설정한 이유가 있을까요?

2024-01-25 07:52 UTC, arky02 commented on business/updateToken.ts
> +const updateToken = async (instance: AxiosInstance) => {
updateToken이라고 하는 것 보다 reissueAccessToken 등 보다 명시적인 이름으로 변경하는게 낫지 않을까요?

2024-01-25 09:15 UTC, Accept77 reviewed
2가지 정도 고민해봤습니다

2024-01-25 09:15 UTC, Accept77 commented on business/updateToken.ts
> +    localStorage.setItem("accessToken", accessToken);
로컬 스토리지에 accessToken저장하는 방식이 좋은 방식인가 고민을 저번에 많이했는데 다른팀들은 중간에 서버를 하나 거치기도 하고 쿠키에 삽입하는 방식도 있던데 고민해봐야 할 것 같습니다

2024-01-25 09:15 UTC, Accept77 commented on apis/axios.ts
> +  return { data, status };
loading도 하나 추가해서 스켈레톤ui나 로딩할때 보여주는 ui처리를 하는게 좋지 않을까요?

2024-01-26 04:07 UTC, arky02 commented on apis/axios.ts
> +  return { data, status };
스켈레톤 작업은 구현 마지막쯤에 다른 컴포넌트들이랑 한번에 같이 작업 하는건 어떤가요?

2024-01-26 10:12 UTC, ayden94 commented on apis/axios.ts
> +  return { data, status };
이건 제가 잘 몰라서 그러는데, axios response schema에 loading 프로퍼티가 있나요?

2024-01-26 10:14 UTC, ayden94 commented on business/updateToken.ts
> +    localStorage.setItem("accessToken", accessToken);
저희는 쿠키와 로컬스토리지 둘 다 사용했었습니다. 쿠키는 컨텍스트로 getserversideprops에서 리액트 쿼리로 패치할 때 쓰고, jotai에서 로컬스토리지 아톰을 지원해서 클라 단에서는 로컬스토리지 쪽 데이터를 가져다 썼습니다. 일단 큰 틀에서의 형태를 잡은 거라서요 나중에 또 api 나오고 인가 로직 고민해봐야겠죠 ㅎㅅㅎ

2024-01-26 10:15 UTC, ayden94 commented on apis/axios.ts
> +});
서버 상태에 따라 다르겠지만, 1초는 너무 짧을 때가 있더라고요. 3초랑 5초 사이에서 고민하다가 넉넉하게 5초로 일단 넣어드렸습니다 :)

2024-01-26 10:15 UTC, ayden94 commented on business/updateToken.ts
> +const updateToken = async (instance: AxiosInstance) => {
그 이름도 아주 좋군요 👍

2024-02-05 01:35 UTC, gooma519 approved these changes
LGTM!

2024-02-05 05:02 UTC, arky02 approved these changes
좋습니다 LGTM!

2024-02-05 05:09 UTC, merged